---
title: "Informasjonsskriv"
---

## Formålet med Health and Life Skills (HeaLS)

Vi ønsker å ha med kommuner som skoleeier i en nasjonal skoleforskningsstudie om det tverrfaglige temaet [Folkehelse og livsmestring](https://www.udir.no/lk20/overordnet-del/prinsipper-for-laring-utvikling-og-danning/tverrfaglige-temaer/folkehelse-og-livsmestring/?lang=nob). Målet med studien er å samle inn informasjon fra skolene for å studere hva som skal til for å lykkes med å fremme *Folkehelse og livsmestring* gjennom undervisningen.

## Hvem er ansvarlig for forskningsprosjektet?

Prosjektet ledes av [Psykologisk institutt ved UiO](https://www.sv.uio.no/psi/personer/vit/egilny/), mens [NIFU](https://www.nifu.no) har hovedansvar for datainnsamlingen. UiO og NIFU har felles databehandleransvar, men kun NIFU håndterer personidentifiserende opplysninger. I tillegg deltar [flere andre organisasjoner](../3_for_forskere/08_prosjektgruppen.qmd). Prosjektet er enestående i sitt slag, og prosjektet vekker internasjonal oppmerksomhet. Derfor [ble det finansiert av det europeiske forskningsrådet (ERC)](https://www.sv.uio.no/om/aktuelt/aktuelle-saker/2023/erc-consolidator-grant-til-psykologisk-institutt.html).

## Hva innebærer det for kommunen å delta?

Deltakelse innebærer at en kommunens representant besvarer en spørreundersøkelse (ca. 20 min) høsten 2024. Undersøkelsen inkluderer spørsmål rundt hvordan ev. intrakommunalt og interkommunalt arbeid med det tverrfaglige temaet Folkehelse og livsmestring foregår. Selv om kommunen ikke skulle ha en dedikert strategi eller dedikerte ansvarlige for dette er det ønskelig at dere blir med. Deres svar vil gjøre at vi trenger færre spørsmål til skolene, og dermed blir det mindre belastning på skolene. Undersøkelsene er nettbaserte. Det er også flere [fordeler](01_kommuner_invitasjon.qmd) ved å delta.

## Hvilke andre typer opplysninger blir samlet inn?

For at forskerne bedre skal forstå hvordan spørsmålene fungerer og hvordan undersøkelsen oppleves, gis det mulighet for å uttrykke seg om dette. Svar på disse spørsmålene benyttes ikke i videre forskning etter at kvalitetssikringsperioden er over. Det samles også inn teknisk prosessdata som eksempelvis type nettleser brukt, IP-adresse, og tid brukt på enkeltspørsmål og undersøkelsen totalt, som fjernes like etter undersøkelsen lukkes.

## Det er frivillig å delta

Det er frivillig å delta i prosjektet. Hvis du velger å delta, kan du når som helst trekke samtykket tilbake uten å oppgi noen grunn. Alle dine personopplysninger vil da bli slettet. Det vil ikke ha noen negative konsekvenser for deg hvis du ikke vil delta eller senere velger å trekke deg. Det er lov å hoppe over spørsmål eller avbryte besvarelsen underveis.

## Kort om personvern

Vi vil bare bruke opplysningene om deg til formålene vi har fortalt om i dette skrivet. Vi behandler personopplysningene konfidensielt og i samsvar med personvernregelverket. Du kan lese [mer utdypende om personvern her](03_kommuner_rekruttering_personvern_utdypende.qmd).

Med vennlig hilsen

| Egil Nygaard       | Cay Gjerustad         |
|--------------------|-----------------------|
| Prosjektleder, UiO | Forskningsleder, NIFU |
