# HeaLS: Folkehelse og livsmestring i skolen

Innføringen av *folkehelse og livsmestring* som tverrfaglig tema i skolen skal bidra til å løse samfunnsproblemer rundt helse, livskvalitet, skoleprestasjoner og frafall. Her trenger vi mer kunnskap, både i Norge og internasjonalt:

-   Hvordan foregår opplæringen i folkehelse og livsmestring, og kan variasjonen mellom skoler og mellom lærere fortelle oss hva som fungerer best?

-   Hvilke lokale forhold tilrettelegger for eller hindrer god undervisning i temaet?

-   Kan det å lære om *folkehelse og livsmestring* på skolen påvirke elevenes mentale helse over tid?

Skolenes egne erfaringer er avgjørende for å forstå hvordan dette fungerer i praksis.

Vi håper derfor at norske grunnskoler og videregående skoler vil delta i en nasjonal undersøkelse. Forskningsprosjektet heter HeaLS og ledes av UiO, og gjennomføres i samarbeid med NIFU.

Deltakelse innebærer en spørreundersøkelse til et knippe lærere, og en til én representant for skoleledelsen. Spørreundersøkelsen sendes ut til skoleleder og lærere rundt **15. oktober** 2024. Det tar 15-20 minutter å svare på undersøkelsene, som også er mobilvennlige.

Du kan også lese mer om hvordan vi håndterer [personvern](../personvern/01_skoler_rekruttering_personvern_grunnleggende.qmd).

# Hva får skolene og kommunen igjen for å delta?

-   **Alle** lærere, skoleledere og skoleeiere som svarer på spørreundersøkelsen, deltar i trekning av 50 gavekort fra DittGavekort.no på 2 000 kr (odds er bedre enn 1:400) som kan benyttes i hele Norge. Vinnere kunngjøres våren 2025 på [heals.nifu.no/nyheter](../nyheter/index.qmd) og per e-post.

-   **Skoler**, med svar fra skoleleder og minst 2 lærere, deltar i trekning av 3 premier av verdi 10 000 kr (odds er bedre enn 1:1000). Vinnere kunngjøres våren 2025 på [heals.nifu.no/nyheter](../nyheter/index.qmd) og per e-post.

-   **Alle** som svarer på spørreundersøkelsen inviteres til 1-2 timers webinar innen prosjektslutt, med faglig påfyll om undervisning i *folkehelse og livsmestring* fra erfarne forskere og lærere, og presentasjon av foreløpige funn fra spørreundersøkelsene.

-   **Skoler** med svar fra nok lærere vil få tilbakemeldinger på hvordan lærerne ved skolen har svart sammenlignet med resten av landet. Ved for få svar aggregerer vi opp til kommunen av anonymitetshensyn.

-   **Skoler** får tilgang på et refleksjonsopplegg for kollektiv profesjonsutvikling om undervisning i *folkehelse og livsmestring*. Opplegget er gruppebasert og kan gjennomføres i fellestid. Det består av faglig påfyll og praksisfortellinger samt oppgaver for refleksjon og diskusjon. Tiltaket gjøres tilgjengelig digitalt våren 2025.

-   **Kommuner** vil få tilbakemelding på hvordan skolene i kommunen har svart sammenlignet med resten av landet. Tilbakemeldinger til skoler og kommuner, samt refleksjonsopplegget, tilgjengeliggjøres på passordbeskyttede nettsider våren 2025.

Jo flere skoler som vi vet deltar, før sommeren begynner, dess færre lærere per skole trenger vi å invitere til spørreundersøkelsene.
