Målet med studien er å samle inn informasjon fra skolene for å studere hva som skal til for å lykkes med å fremme *Folkehelse og livsmestring* gjennom undervisningen.

## Hvem er ansvarlig for undersøkelsene?

*HeaLS* ledes av [Psykologisk institutt ved UiO](https://www.sv.uio.no/psi/english/research/projects/heals/index.html), mens [NIFU](https://www.nifu.no) har hovedansvar for datainnsamlingen. *LIFE* ledes av [Skolemiljøsenteret ved UiS](https://www.uis.no/nb/laeringsmiljosenteret/forskning/life-livsmestring-i-teori-og-praksis). UiO, NIFU og UiS har felles databehandleransvar, men kun NIFU og UiS håndterer personidentifiserende opplysninger. I tillegg deltar [folk fra andre organisasjoner](../5_for_forskere/08_prosjektgruppen.qmd). Prosjektetene er enestående i sitt slag, og prosjektet vekker internasjonal oppmerksomhet. Derfor [ble HeaLS finansiert av Det europeiske forskningsrådet (ERC)](https://www.sv.uio.no/om/aktuelt/aktuelle-saker/2023/erc-consolidator-grant-til-psykologisk-institutt.html) og [LIFE av Forskningsrådet](https://www.forskningsradet.no/nyheter/2023/124-millioner-til-a-forske-pa-utdanning-og-laring/).
