project:
  type: website
  execute-dir: project

website:
  title: "HeaLS og LIFE: Folkehelse og livsmestring i skolen"
  repo-url: "https://github.com/NIFU-NO/heals.nifu.no"
  repo-subdir: "_site"
  search: true
  draft-mode: unlinked
  page-navigation: true
  reader-mode: true
  navbar:
    left:
      - sidebar:news
      - sidebar:schools
      - sidebar:municipalities
      - sidebar:counties
      - sidebar:researchers
      - sidebar:presentation
  sidebar: 
    - id: news
      title: "Nyheter"
      contents: 0_nyheter
    - id: schools
      title: "For skoler"
      contents: 1_for_skoler
    - id: municipalities
      title: "For kommuner"
      contents: 2_for_kommuner
    - id: counties
      title: "For fylkeskommuner"
      contents: 3_for_fylkeskommuner
    - id: researchers
      title: "Mer om prosjektet"
      contents: 5_for_forskere
    - id: presentation
      title: "PowerPoint-presentasjon"
      contents: kort_presentasjon
  site-url: "heals.nifu.no"
execute:
  echo: false
  warning: false
  message: false
  cache: true
  freeze: auto

fig-dpi: 800
crossref:
 chapters: true
 fig-title: '**Figur**'
 tbl-title: '**Tabell**'
 lof-title: 'Figuroversikt'
 lot-title: 'Tabelloversikt'
 title-delim: '**.**'
 fig-prefix: figur
 tbl-prefix: tabell
 ref-hyperlink: true
 labels: arabic
# custom:
#  - kind: float
#    reference-prefix: Figur
#    key: fig
#  - kind: float
#    reference-prefix: Tabell
#    key: tbl
fig-cap-location: bottom
tbl-cap-location: top
csl: 5_for_forskere/style.csl

lang: "nb"
license: "CC BY 4.0"
format:
  # typst: default
  html:
    mainfont: "Calibri"
    fontsize: "10.5"
    linestretch: 1.6
    theme:
      light: [yeti, styles.scss]
      dark: darkly
    css: "styles.css"
    toc: true
    comments:
      hypothesis: true
    include-after-body:
      text: |
        <script>
          document.addEventListener("DOMContentLoaded", () => {
            document.querySelectorAll("figcaption").forEach(e => {e.innerHTML = e.innerHTML.replace(/^(Figur&nbsp;\d+)/, "<strong>$1</strong>")})
          });
        </script>
