project:
  type: website

website:
  title: "heals.nifu.no"
  navbar:
    left:
      - href: "nyheter/index.qmd"
        text: "Nyheter"
      - href: "personvern/index.qmd"
        text: "Personvern"
      - href: "om_prosjektet/index.qmd"
        text: "Om HeaLS"
  sidebar: 
    contents: auto
  site-url: "heals.nifu.no"
  
csl: style.csl
execute:
  echo: false
  warning: false
  message: false
  cache: true
  freeze: true