project:
  type: website
  execute-dir: project
  post-render: "_extensions/remove_menu_links.R"

website:
  title: "HeaLS og LIFE: Folkehelse og livsmestring i skolen"
  repo-url: "https://github.com/NIFU-NO/heals.nifu.no"
  repo-subdir: "_site"
  search: true
  draft-mode: gone
  page-navigation: true
  reader-mode: true
  drafts:
    - "./1_for_skoler/10_skoleleder_epost.qmd"
    - "./1_for_larere/10_larer_epost_lang.qmd"
    - "./1_for_larere/10_larer_epost_logg.qmd"
    - "./2_for_kommuner/10_skoleeier_kom_epost.qmd"
    - "./3_for_fylkeskommuner/10_skoleeier_fyl_epost.qmd"
  navbar:
    left:
      - sidebar:news
      - sidebar:schools
#      - sidebar:teachers
      - sidebar:municipalities
      - sidebar:counties
      - sidebar:researchers
      - sidebar:presentation
  sidebar: 
    - id: news
      title: "Nyheter"
      contents: 0_nyheter
#    - id: teachers
#      title: "For inviterte respondenter"
#      contents: 1_for_larere
    - id: schools
      title: "For skoler"
      contents: 1_for_skoler
    - id: municipalities
      title: "For kommuner"
      contents: 2_for_kommuner
    - id: counties
      title: "For fylkeskommuner"
      contents: 3_for_fylkeskommuner
    - id: researchers
      title: "Mer om prosjektene"
      contents: 
      - 5_for_forskere/08_prosjektgruppen.qmd
      - 5_for_forskere/09_finansiering.qmd
      - 5_for_forskere/07_publikasjoner.qmd
    - id: presentation
      title: "PowerPoint-presentasjon"
      contents: kort_presentasjon
  site-url: "heals.nifu.no"
execute:
  echo: false
  warning: false
  message: false
  cache: true
  freeze: auto
format-links:
  - html
  - format: typst
    text: PDF
    icon: file-pdf
  - docx
fig-dpi: 800
crossref:
 chapters: true
 fig-title: '**Figur**'
 tbl-title: '**Tabell**'
 lof-title: 'Figuroversikt'
 lot-title: 'Tabelloversikt'
 title-delim: '**.**'
 fig-prefix: figur
 tbl-prefix: tabell
 ref-hyperlink: true
 labels: arabic
# custom:
#  - kind: float
#    reference-prefix: Figur
#    key: fig
#  - kind: float
#    reference-prefix: Tabell
#    key: tbl
fig-cap-location: bottom
tbl-cap-location: top
csl: 5_for_forskere/style.csl

lang: "nb"
format:
  html:
    mainfont: "Calibri"
    fontsize: "10.5"
    linestretch: 1.6
    theme:
      light: [yeti, styles.scss]
      dark: darkly
    css: "styles.css"
    toc: true
    comments:
      hypothesis: true
    include-after-body:
      text: |
        <script>
          document.addEventListener("DOMContentLoaded", () => {
            document.querySelectorAll("figcaption").forEach(e => {e.innerHTML = e.innerHTML.replace(/^(Figur&nbsp;\d+)/, "<strong>$1</strong>")})
          });
        </script>
