project:
  type: website
  execute-dir: project

website:
  title: "HeaLS: Folkehelse og livsmestring i skolen"
  repo-url: "https://github.com/NIFU-NO/heals.nifu.no"
  repo-subdir: "_site"
  search: true
  draft-mode: unlinked
  page-navigation: true
  reader-mode: true
  navbar:
    left:
      - href: "0_nyheter/index.qmd"
        id: news
      - href: "1_for_skoler/index.qmd"
        id: schools
      - href: "2_for_kommuner/index.qmd"
        id: municipalities
      - href: "3_for_forskere/index.qmd"
        id: researchers
  sidebar: 
    contents: auto
  site-url: "heals.nifu.no"
fig-dpi: 800
crossref:
 chapters: true
 fig-title: '**Figur**'
 tbl-title: '**Tabell**'
 lof-title: 'Figuroversikt'
 lot-title: 'Tabelloversikt'
 title-delim: '**.**'
 fig-prefix: Figur
 tbl-prefix: Tabell
 ref-hyperlink: true
 labels: arabic
# custom:
#  - kind: float
#    reference-prefix: Figur
#    key: fig
#  - kind: float
#    reference-prefix: Tabell
#    key: tbl
fig-cap-location: bottom
tbl-cap-location: top
csl: 3_for_forskere/style.csl

lang: "nb"
license: "CC BY 4.0"
format:
  typst: default
  html:
    mainfont: "Calibri"
    fontsize: "10.5"
    linestretch: 1.6
    theme:
     - yeti
     # - "styles.scss"
    css: "styles.css"
    toc: true
    comments:
      hypothesis: true
    include-after-body:
      text: |
        <script>
          document.addEventListener("DOMContentLoaded", () => {
            document.querySelectorAll("figcaption").forEach(e => {e.innerHTML = e.innerHTML.replace(/^(Figur&nbsp;\d+)/, "<strong>$1</strong>")})
          });
        </script>


execute:
  echo: false
  warning: false
  message: false
  cache: true
  freeze: auto

