---
title: "Forskning på folkehelse og livsmestring i skolen"
subtitle: Delta i Norges største prosjekt om hvordan vi kan styrke implementering av og undervisning i folkehelse og livsmestring, og gi lærerne mulighet til å sette ord på utfordringene!
callout-appearance: simple
callout-icon: false
---

::: {layout="[[70,30]]"}

::: {.callout-note title="Ønsker din skole å bli med?"}

Representant for skoleledelse kan [klikke her](https://nifueu.qualtrics.com/jfe/form/SV_aaDR9MONUSCYHz0) for å melde interesse.

Om skoleeier ikke har mottatt epost, [trykk her for en ferdigutfylt epost](mailto:heals@nifu.no?subject=Vi%20vil%20gjerne%20delta&body=Hei,%0Avi%20er%20interesserte%20i%20prosjektet%20og%20vil%20gjerne%20motta%20påmeldingsinformasjon.%0A%0AHilsen%20KOMMUNE) som enkelt kan sendes oss.

Se også sidene i menyen ovenfor for informasjon om hva deltakelse innebærer for dere.

Til dere som mottok invitasjon fra HeaLS i våres: Datainnsamling ble utsatt for at [HeaLS](https://www.sv.uio.no/psi/english/research/projects/heals/index.html) og [LIFE](https://www.uis.no/nb/laeringsmiljosenteret/forskning/life-livsmestring-i-teori-og-praksis) skulle kunne samarbeide om datainnsamlingen.

:::

{{< video kort_presentasjon/kort_infovideo.m4v >}}

:::


## Bakgrunn


Ny læreplan LK20 ("fagfornyelsen") ga eksplisitt oppføring av [*Folkehelse og livsmestring*](https://www.udir.no/lk20/overordnet-del/prinsipper-for-laring-utvikling-og-danning/tverrfaglige-temaer/folkehelse-og-livsmestring/?lang=nob), med store målsettinger. Men det er lite detaljer om konkrete kompetansemål og hvordan det undervises. Derfor er det opp til skolene og lærerne lokalt hvordan mål skal omsettes til praksis. Samtidig er det store variasjoner mellom skoler i elevmassens behov, lokale muligheter/utfordringer og lærerbakgrunner. I tillegg er det en tidsdimensjon: Implementeringen endres over tid, og lærere kan ha ulike fag og elever over tid. Slik variasjon er nyttig for skoleforskere!

::: {.column-margin}

::: {.callout-tip title="Oppl.lov. § 9A-2"}
_Alle elevar har rett til eit trygt og godt skolemiljø som fremjar helse, trivsel og læring_
:::
:::


## Våre formål

[_Folkehelse og livsmestring som tverrfaglig tema i skolen skal gi elevene kompetanse som fremmer god psykisk og fysisk helse, og som gir muligheter til å ta ansvarlige livsvalg._ (LK20)]{.aside}

-   Vi vil undersøke hvordan foregår opplæringen i folkehelse og livsmestring
-   Vi vil også undersøke hvordan variasjoner i måten skoleeiere, skoler og lærere jobber med temaet påvirker skolemiljøet og elevenes mentale helse, skoleprestasjoner og frafall
-   Lærere vil få anledning til å uttrykke seg om utfordringer de har med å møte elevenes behov for støtte omkring psykisk helse, og skolens behov for å styrke skolemiljøet

## Informasjonsmøter

[Klikk her for å legge til kalenderoppføring for informasjonsmøtet 5. oktober](Infomote_2024-10-05.ics).