Din skoleledelse vil ikke få vite dine svar eller om du har svart. Spørreskjemaet kan gjennomføres på mobil. For å delta klikker du her: **LENKE**

## Hva får du igjen for å delta?
Deltakere får [flere fordeler](https://heals.nifu.no/1_for_skoler/01_skoler_invitasjon.html#sec-fordeler-skoler): et webinar om funn fra prosjektet (før alle andre får kunnskapen), trekning av gavekort blant respondenter og skoler, et refleksjonsopplegg om folkehelse og livsmestring, og beskyttet tilgang til skolens svar sammenliknet med andre (forutsetter nok svar ved skolen til at det blir anonymt).

Undersøkelsen er et samarbeid mellom forskningsprosjektene [HeaLS](https://heals.nifu.no) (ledet av UiO, sammen med NIFU) og [LIFE](https://www.uis.no/nb/laeringsmiljosenteret/forskning/life-livsmestring-i-teori-og-praksis) (ledet av UiS). 

## Mer informasjon?
Du får mer informasjon om personvern og hva studien innebærer [her](https://heals.nifu.no/).
Nettstedet inneholder blant annet en [kort presentasjon](https://heals.nifu.no/kort_presentasjon/). Svar oss gjerne på denne eposten om du har spørsmål.

På vegne av HeaLS og LIFE-prosjektene,

- Prosjektleder i HeaLS, Egil Nygaard, UiO
- Forskningsleder Cay Gjerustad, NIFU
- Prosjektleder i LIFE, Hildegunn Fandrem, UiS

Om du ikke ønsker å delta kan du klikke her **LENKE2**.


