Andre i kommunen vil ikke få se dine svar. Spørreskjemaet kan gjennomføres på mobil. For å delta klikker du på lenken: **LENKE**

## Hva får dere igjen for å delta?
Deltakere får [flere fordeler](https://heals.nifu.no/2_for_kommuner/01_kommuner_invitasjon.html#sec-fordeler-kommuner): et webinar om funn fra prosjektet (før alle andre får kunnskapen), trekning av gavekort blant respondenter (personlig gave, ikke til kommunen), et refleksjonsopplegg om folkehelse og livsmestring, og beskyttet tilgang til kommunens svar sammenliknet med andre (forutsetter nok svar i kommunen til at det blir anonymt).

Undersøkelsen gjennomføres av forskningsprosjektet [HeaLS](https://heals.nifu.no) (ledet av UiO, sammen med NIFU). 

## Mer informasjon?
Du får mer informasjon om personvern og hva studien innebærer [her](https://heals.nifu.no/).
Nettstedet inneholder blant annet en [kort presentasjon](https://heals.nifu.no/kort_presentasjon/). Svar oss gjerne på denne eposten om du har spørsmål.

På vegne av HeaLS og LIFE-prosjektene,

- Prosjektleder i HeaLS, Egil Nygaard, UiO
- Forskningsleder Cay Gjerustad, NIFU


For mer informasjon om personvern og påmelding, klikk her: **LENKE**



^Om du ikke ønsker å delta kan du klikke her: **LENKE2**.^
