---
title: "Epost: Spørreundersøkelse om ditt og deres arbeid med folkehelse og livsmestring"
format: 
  html: default
  typst: default
  docx: default
---

## Kjære **FORNAVN**

**VIRKSOMHET** har ytret ønske om å delta i en undersøkelse om hvordan skolen kan bidra til bedre skolemiljø og styrke deres elevers livsmestring. Vi ønsker å utforske beste praksis i skolen og blant skoleeiere om implementeringen av det tverrfaglige temaet folkehelse og livsmestring. Med ditt bidrag kan vi finne ut hvordan vi øker trivsel på skolen, bedrer den mentale helsen og forebygger frafall hos elever.

- Vi har ved **VIRKSOMHET** trukket ut deg til å bli invitert til en spørreundersøkelse som tar 15-20 minutter. Dine svar vil bidra til å **MÅLGRUPPESPESIFIKKE UTBYTTER**.

- Vi har ved **VIRKSOMHET** trukket ut deg til å bli invitert til en veldig kort spørreundersøkelse (3-5 minutter) og en kort logg (2 minutter) etter fire undervisningsøkter. Læreres logger vil gi oss innblikk i hvordan temaet undervises på tvers av ulike kontekster, slik som fag, slik at vi kan finne ut hva som fungerer og ikke.

- Vi inviterer derfor deg som representant for skoleledelsen i **VIRKSOMHET** til en spørreundersøkelse som tar 15-20 minutter. Dine svar vil bidra til å **MÅLGRUPPESPESIFIKKE UTBYTTER**.

- Vi inviterer derfor deg som representant for skoleeier i **VIRKSOMHET** til en spørreundersøkelse som tar 20-24 minutter. Dine svar vil bidra til å avdekke hvordan skoleeiers relasjon pleier å være mellom skole og nasjonale føringer. 


Verken din arbeidsgiver eller andre får vite dine svar eller om du har svart. Undersøkelsene er nettbaserte og fungerer godt på mobiltelefon.

## Hva får du igjen for å delta?
Deltakere får [flere fordeler](https://heals.nifu.no/1_for_skoler/01_skoler_invitasjon.html#sec-fordeler-skoler): et webinar om funn fra prosjektet (før alle andre får kunnskapen), trekning av gavekort blant respondenter og skoler, et refleksjonsopplegg om folkehelse og livsmestring, og beskyttet tilgang til skolens svar sammenliknet med andre (forutsetter nok svar ved skolen til at det blir anonymt).

Undersøkelsen gjennomføres av forskningsprosjektet [HeaLS](https://heals.nifu.no) (ledet av UiO, sammen med NIFU). 

## Mer informasjon?
Du får mer informasjon om personvern og hva studien innebærer [her](https://heals.nifu.no/).
Nettstedet inneholder blant annet en [kort presentasjon](https://heals.nifu.no/kort_presentasjon/). Svar oss gjerne på denne eposten om du har spørsmål.

På vegne av HeaLS,

- Prosjektleder i HeaLS, Egil Nygaard, UiO
- Forskningsleder Cay Gjerustad, NIFU

For mer informasjon om personvern og påmelding, klikk her: **LENKE**



<sup>Om du ikke ønsker å delta kan du klikke her: **LENKE2**.</sup>


