Spørreskjemaet kan gjennomføres på mobil. 

## Hva får du igjen for å delta?
Deltakere får [flere fordeler](https://heals.nifu.no/1_for_skoler/01_skoler_invitasjon.html#sec-fordeler-skoler): et webinar om funn fra prosjektet (før alle andre får kunnskapen), trekning av gavekort blant respondenter og skoler, et refleksjonsopplegg om folkehelse og livsmestring, og beskyttet tilgang til skolens svar sammenliknet med andre (forutsetter nok svar ved skolen til at det blir anonymt).

Undersøkelsen gjennomføres av forskningsprosjektet [HeaLS](https://heals.nifu.no) (ledet av UiO, sammen med NIFU). 

## Mer informasjon?
Du får mer informasjon om personvern og hva studien innebærer [her](https://heals.nifu.no/).
Nettstedet inneholder blant annet en [kort presentasjon](https://heals.nifu.no/kort_presentasjon/). Svar oss gjerne på denne eposten om du har spørsmål.

På vegne av HeaLS,

- Prosjektleder i HeaLS, Egil Nygaard, UiO
- Forskningsleder Cay Gjerustad, NIFU

For mer informasjon om personvern og påmelding, klikk her: **LENKE**



<sup>Om du ikke ønsker å delta kan du klikke her: **LENKE2**.</sup>


